### ISSUE TITLE
`./gradlew scalafmt`: org.scalafmt.Error$SearchStateExploded

### ISSUE THREAD

**Issue by dainkaplan** [alenkacz/gradle-scalafmt#15]
Hi. I get this error when I try to run the scalafmt task on the main sourceset:

```
~/projects/foo $ ./gradlew scalafmt
:scalafmt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':scalafmt'.
> org.scalafmt.Error$SearchStateExploded: Search state exploded around line 102
```

It works fine for the test sourceset which is much smaller.

**Comment by alenkacz** [comment]
@dainkaplan interesting... Can you please try to run it with --debug? Also how big is your test sourceset?

**Comment by dainkaplan** [comment]
@alenkacz Nothing particularly interesting with `--debug` but `--stacktrace` revealed that it is coming from `org.scalafmt.internal`:

```
Caused by: org.scalafmt.Error$SearchStateExploded: Search state exploded around line 102
  at org.scalafmt.internal.BestFirstSearch.shortestPath(BestFirstSearch.scala:215)
  at org.scalafmt.internal.BestFirstSearch.getBestPath(BestFirstSearch.scala:271)
  at org.scalafmt.Scalafmt$.format(Scalafmt.scala:53)
  at org.scalafmt.Scalafmt.format(Scalafmt.scala)
  at org.scalafmt.Scalafmt$format.call(Unknown Source)
  at cz.alenkacz.gradle.scalafmt.ScalafmtFormatBase$_runScalafmt_closure2.doCall(ScalafmtFormatBase.groovy:22)
  at cz.alenkacz.gradle.scalafmt.ScalafmtFormatBase.runScalafmt(ScalafmtFormatBase.groovy:19)
  at cz.alenkacz.gradle.scalafmt.ScalafmtFormatBase.runScalafmt(ScalafmtFormatBase.groovy)
  at cz.alenkacz.gradle.scalafmt.ScalafmtFormatBase$runScalafmt.callCurrent(Unknown Source)
  at cz.alenkacz.gradle.scalafmt.ScalafmtTask.format(ScalafmtTask.groovy:8)
  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

I can file an issue on that project!

**Comment by alenkacz** [comment]
@dainkaplan it seems to be known issue of scalafmt. Here you can find some tips on how to get around it http://scalameta.org/scalafmt/#Deeplynestedcode
